import Head from 'next/head'
import Body from '../components/Body'
import Footer from '../components/Footer'
import Header from '../components/Header/Header'

export default function Home() {
  return (
    <>
      <Head>
        <title>Google Clone</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      
      <div className='flex flex-col justify-between h-[100vh]'>
      <header>
        <Header />
      </header>

      <main>
        <Body />
      </main>

      <footer>
        <Footer />
      </footer>
      </div>
    </>
  )
}
